### PR TITLE
Animation branch

### PR DESCRIPTION
**Pull request by kennankole**
Added animation and transition to the site. 

- Animated menu links 
- Animated page transitions 
- Animated Portfolio card images.

### CODE REVIEW

**Review by sja-thedude — COMMENTED** [review]
## Invalid Code Review Request ❌

Hi @kennankole, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, of a different milestone. Kindly make sure to submit link to a pull request or issue which have the live link of deployed website.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by kennankole** [comment]
Hello @sja-thedude 
I have already deployed my app with github pages as specified in the requirements. [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/5_deploy.md#project-requirements) and the live demo can be seen [here](https://kennankole.github.io/portfolio-app/). 

Could you kindly explain to me what I should do from there? 
Do I need to create another pull request upon changing the README.md file which I have already done? Thanks.

**Comment by sja-thedude** [comment]
> Hello @sja-thedude 
> 
> I have already deployed my app with github pages as specified in the requirements. [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/5_deploy.md#project-requirements) and the live demo can be seen [here](https://kennankole.github.io/portfolio-app/). 
> 
> 
> 
> Could you kindly explain to me what I should do from there? 
> 
> Do I need to create another pull request upon changing the README.md file which I have already done? Thanks.

You have to create a new pull request or issue and then you have add the link of deployed page. Also add the link in Readme.
Then you can submit.

**Comment by kennankole** [comment]
Ok.

**Pull request merged**
