### PR TITLE
Desktop

### PR DESCRIPTION
**Pull request by kennankole**
Created desktop version and implemented media queries for responsive web design. 
- I have also created a new pull request after consulting with my previous code review. 
- Here is a link to the thread [PR 12](https://github.com/kennankole/portfolio-app/pull/12).

### CODE REVIEW

**Review by cwaku — CHANGES_REQUESTED** [review]
Hi @kennankole 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
- [x] Correct use of Github flow 👍🏾 
- [x] Linters passed 💯 
- [x] Good overall template design 👍🏾 
- [x] Good PR description 🥇 

## Required Changes ♻️
It's ok to have bugs in your code. Please, see this code review as a chance to learn practical coding skills and new tips 🌟  that can improve your code quality 💯 and help you get a better job 💼.

I will guide 📔 you through fixing 🛠️ these bugs, follow my comments down below and make sure you don't miss any of them to get your project approved ✅

- [ ] Great job putting everything together into a single branch as the previous code reviewer requested, but unfortunately, we are not quite there yet. In your case, you are not supposed to create two different files, `desktop.html` and `index.html` for desktop and mobile versions, respectively. Kindly have only a single `index.html` file and use `CSS` to style it to the screen sizes you want. Please make use of [media queries](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) to add breakpoints for mobile and desktop versions and not two separate HTML files.


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. The previous reviewer simply missed some of them, and addressing them will improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification. You can also WhatsApp me at +233555145007 for a faster response.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kennankole** [comment]
Hello, @cwaku thanks for your responses.
Let me work on the changes you have mentioned. 

However, I would also like to point out that it is possible to have both my mobile and desktop version are in a single file, the deskop.html file. let me try and show this
The desktop.html has both the mobile and desktop version of the portfolio app. 

- **Mobile version beginning at 768px** 
photo1661616251 (1)

**The Desktop version at full screen**
photo1661616251

**Comment by cwaku** [comment]
@kennankole Oh, I see. When reviewing, I first checked the `index.html`, which had only the mobile version and then the `desktop.html`; I didn't switch to the mobile version on `desktop.html`. My apologies but all the same,
- [ ] you'll have to rename the `desktop.html` file to `index.html`. We only create another HTML file for pages and not screen sizes. Also, I'd prefer you move the `index.html` file into your root folder, saving you some configuration time when deploying your app in later milestones.
- [ ] kindly make your mobile version more responsive. Below is what I see when I switch to the mobile screen on the `desktop.html` file. 

Your Design | Figma Design
--|--
image | image

Implement the above, and you'll be in an excellent position to get your project approved.

**Comment by kennankole** [comment]
Hello @cwaku could you kindly tell me which part does not correspond to the Figma design so that I know what to change?
Thanks.

**Comment by cwaku** [comment]
@kennankole  It's not quite responsive, hence a lot of space to the right as you can see in the screenshot above. Kindly make fix that.

**Comment by kennankole** [comment]
How can I remove this space on the left? 
Do you have any suggestions? 
I have tried with no avail

**Comment by cwaku** [comment]
> How can I remove this space on the left? Do you have any suggestions? I have tried with no avail

@kennankole The width of the `class: main-background` and its children are causing that. I'd suggest you use flexbox instead of grid. Flexbox helps with a lot of auto-adjusting for you and makes it easier to style. Also, consider removing the hard width of its children.

**Review by BertrandConxy — CHANGES_REQUESTED** [review]
hi @kennankole , 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 💪 
- No linter errors
- correct flow is used
- good improvement based on the previous reviewer's suggestions
- good communication with reviewer


 ## Required Changes ♻️

- [ ] I think the issue pointed out by the previous reviewer is not yet solved because this margin around the page is still visible. I found out that it is being caused by the styles applied to the body from the user-agent stylesheet which you don't have control of. 

👇  I hope you can see where there are body style properties with an indication of the _user-agent stylesheet_. When you hover on it, it is where you find out where that margin of 8px is coming from.
Screenshot (104)
This is the first time is saw this bug. I tried to read articles that talks about it and I think there is a way you can override these styles coming from the user-agent stylesheet. Please read these [article 1](https://stackoverflow.com/questions/12582624/what-is-a-user-agent-stylesheet) and [article 2](https://marksheet.io/css-reset.html) I hope that they will help you figure out the solution for this. Keep the hard work @kennankole  😃 

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kennankole** [comment]
Hello @BertrandConxy 
I managed to override the 8px margin user agent stylesheet 
Below is a screencast of what I have accomplished

[Screencast from 28-08-2022  7:47:11 WB.webm](https://user-images.githubusercontent.com/39535023/187085398-dcd6f80a-daed-4c1b-b9b1-5b8a712f714d.webm)

Let me know if I have solved it correctly 
Thanks.

**Comment by BertrandConxy** [comment]
I think it looks good now

**Comment by BertrandConxy** [comment]
👏👏👏

**Pull request merged**
