### PR TITLE
Mobile first

### PR DESCRIPTION
**Pull request by kennankole**
Created the desktop version of the portfolio app.

### CODE REVIEW

**Review by 1GORDON — CHANGES_REQUESTED** [review]
##
## Hi @kennankole ✋ 

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] Great job on implementing the design. However, you implemented a mobile version only. According to [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md), you are supposed to design both the `mobile version` and `desktop version`. This is achievable by the use of media queries in your stylesheet. 

- Your design
Your design


_Check the comments under the review._

## Optional suggestions

- [ ] Kindly make sure your branch name is created off of the `main` branch or `master` branch. I can see you created your branch `mobile-first` off of another feature branch `landing-page`. This `landing-page` branch should instead be the `main` branch.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kennankole** [comment]
Thanks @1GORDON 
I have developed the desktop version of the portfolio app and this is what is in the landing-page branch that I now want to merge to the mobile-first-branch. 
Screenshot from 2022-08-26 08-44-02

The desktop version is what is contained in the landing-page branch that I now want to merge to the mobile-first branch. Could you kindly help me understand what you mean that I have only developed the mobile version?

**Comment by 1GORDON** [comment]
Thank you for your question @kennankole. The requirement for this project is to have one branch containing both the desktop version and the mobile version. You are not supposed to create two branches for each version. Hopefully, you will understand the milestone if you read the project requirement again. This approach of mobile-first can be better achieved by using media queries in your stylesheet.
- Remember, this is why I had suggested your branch be merged into the main, not into another feature branch. Kindly check my optional suggestion in the main comment.

**Comment by 1GORDON** [comment]
Hello, again @kennankole ✋

- [ ] Kindly update me if you fail to understand the requirement. I will be glad to join a zoom call and narrate to you better. Kindly slack me on, Tinyefuza Gordon. I will be happy to help. Thank you.

**Comment by kennankole** [comment]
Yes, I think a zoom call will be great so that you help me out on media queries that I don't seem to understand. 
 Thanks @1GORDON

**Comment by 1GORDON** [comment]
That's very fine @kennankole. Can we join the call after the morning session? That's at 9 am microverse time.

**Comment by kennankole** [comment]
That will be great. How about now so that I have more time to implement the changes

**Comment by 1GORDON** [comment]
Hello, @kennankole 
- Kindly contact me after your morning session. Or when you get free

**Comment by kennankole** [comment]
Hello @1GORDON am free now

**Comment by kennankole** [comment]
Hi @1GORDON 
I have realized that I need to merge my desktop version to the main branch and not to the mobile-first branch. As such, I will have to create a new pull request and specify in the PR comments why this new pull request. 
Thanks again for your input

Alt Text

**Comment by 1GORDON** [comment]
You are welcome @kennankole 👌 and good luck with the project. 
- You may use markdown syntax for that comment about the reason you have created a new branch. This will make the comment more visible and guide the reviewer better.

**Pull request closed without merging**
